# Generated by Django 4.2.10 on 2026-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Javob varianti', 'verbose_name_plural': 'Javob variantlari'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': "Qo'llanma", 'verbose_name_plural': "Qo'llanmalar"},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Laboratoriya', 'verbose_name_plural': 'Laboratoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='practical',
            options={'verbose_name': "Amaliy mashg'ulot", 'verbose_name_plural': "Amaliy mashg'ulotlar"},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Taqdimot', 'verbose_name_plural': 'Taqdimotlar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterModelOptions(
            name='testaccesstoken',
            options={'verbose_name': 'Test tokeni', 'verbose_name_plural': 'Test tokenlari'},
        ),
        migrations.AlterModelOptions(
            name='testattempt',
            options={'verbose_name': 'Test urinish', 'verbose_name_plural': 'Test urinishlar'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AddField(
            model_name='test',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tests/'),
        ),
    ]
