# Generated by Django 4.2.10 on 2026-02-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAccessToken',
        ),
    ]
